# Generated by Django 3.2.4 on 2021-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Plans', models.CharField(max_length=100)),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
