# Generated by Django 3.2.4 on 2021-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_client_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Plans',
            field=models.CharField(max_length=100),
        ),
    ]
