# Generated by Django 3.2.4 on 2021-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Status',
            field=models.BooleanField(max_length=1),
        ),
    ]
