# Generated by Django 3.2.4 on 2021-07-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Plans', models.IntegerField(max_length=100)),
                ('Status', models.BooleanField(max_length=1)),
            ],
        ),
    ]
